// =====================================================================
// Attencity — site identity, navigation, and page copy in one place.
//
// Sources (docs/content-update-plan.md §3): the 2026 one-pager, the 31-slide
// 2026 Business Deck, and the copy captured from attencity.com on 2026-09-02.
// Long reference data lives next door:
//   services.js  — the seven services and their landing pages
//   network.js   — clients, media network, evidenced placements
//   posts.js     — case studies + insights loaded from src/content/*.md
// Anything still marked `interim: true` is stand-in text awaiting the owner.
// =====================================================================
import { base } from '$app/paths';
import { assetRoot } from '$lib/wp/runtime.js';
import { mediaSizes } from './media-sizes.js';

export { services, companyServices, serviceBySlug } from './services.js';
export { clientLogos, clientCategories, networkGroups, placements } from './network.js';

/**
 * Absolute path to a file in static/assets/attencity/.
 * `assetRoot()` is `base` in the static build and the WordPress theme
 * directory in the WP_BUILD shell — see src/lib/wp/runtime.js.
 */
export const asset = (file) => `${assetRoot()}/assets/attencity/${file}`;
/** Base-aware internal route. Routes always end with a slash (trailingSlash = 'always'). */
export const route = (path) => `${base}${path}`;
/** `[width, height]` for any WebP under static/assets/attencity/, or null. */
export const dims = (file) => {
	const m = mediaSizes[file];
	return m ? { width: m[0], height: m[1] } : null;
};
/**
 * srcset for a WebP that also has an 800px `-800.webp` sibling. Widths come
 * from media-sizes.js (generated by scripts/build-assets.py), so they can
 * never drift from the files on disk. Returns '' when there is no sibling —
 * bind it with `srcset={srcset(f) || undefined}`.
 */
export const srcset = (file) => {
	const m = mediaSizes[file];
	if (!m || !m[2]) return '';
	return `${asset(file.replace(/\.webp$/, '-800.webp'))} 800w, ${asset(file)} ${m[0]}w`;
};

export const site = {
	name: 'Attencity',
	/** §10 Q6 — the one-pager prints both; default to the registered form. */
	legalName: 'Attencity Marketing LLC',
	tagline: 'Attention meets City!',
	promise: 'Your long-term partner for cross-market, cross-city growth.',
	url: 'https://attencity.com',
	description:
		'Attencity is a New York marketing and communications agency helping brands localize deeply and grow sustainably in global markets.',
	ogImage: 'og/home.jpg',
	founded: '2023',
	foundedIn: 'New York, 2023',
	logo: 'logo-attencity.png',
	contact: {
		street: '411 West 35th Street, 6th Floor',
		locality: 'New York',
		region: 'NY',
		postalCode: '10001',
		country: 'US',
		countryName: 'United States',
		get address() {
			return `${this.street}, ${this.locality}, ${this.region} ${this.postalCode}`;
		},
		mapQuery: '411 W 35th St, New York, NY 10001',
		phone: '+1 (332) 999-3472',
		email: 'communications@attencity.com',
		areaServed: ['United States', 'China']
	},
	/** `href: ''` renders as a QR/handle instead of a link. `hidden` keeps an
	 *  account out of the site entirely (§10 Q3 — personal WeChat). */
	social: [
		{
			name: 'Instagram',
			icon: 'instagram',
			handle: '@attencitymarketing',
			href: 'https://www.instagram.com/attencitymarketing/'
		},
		{
			name: 'TikTok',
			icon: 'tiktok',
			handle: '@attencity_marketing',
			href: 'https://www.tiktok.com/@attencity_marketing'
		},
		{
			name: 'Xiaohongshu (RedNote)',
			shortName: 'RedNote',
			icon: 'xiaohongshu',
			handle: '纽约搞事小组',
			note: 'Xiaohongshu ID 6782513500',
			href: '', // §10 Q3 — profile URL still needed; the QR + ID work meanwhile
			qr: 'contact/xiaohongshu-qr.webp',
			qrAlt: 'Xiaohongshu profile card for 纽约搞事小组, Xiaohongshu ID 6782513500'
		},
		{
			name: 'WeChat',
			icon: 'wechat',
			handle: 'Icelynn',
			href: '',
			qr: 'contact/wechat-qr.webp',
			qrAlt: 'WeChat add-friend QR code',
			// §10 Q3 — the only QR we have is a personal account. Flip to false
			// once the owner confirms, or supplies an official-account QR.
			hidden: true
		}
	],
	/** Measurement. No GA4 property existed as of 2026-09-07 — the owner creates
	 *  one and pastes the G-XXXXXXXXXX id here; the tag renders only when set. */
	analytics: {
		ga4Id: ''
	},
	/** Attencity is Shanghai Media Group's strategic partner in North America. */
	partnership: {
		title: 'Shanghai Media Group × Attencity',
		body: 'Attencity is Shanghai Media Group’s official strategic partner in North America. Since 2024, “SMG × Attencity” has been CES’s sole official Chinese-language media partner, leading the creation and on-the-ground execution of the Speed Award World Tech Summit · China Day.'
	}
};

/** Proof numbers — use these everywhere rather than re-typing figures (§3.3). */
export const stats = {
	outlets: { value: '1,000+', label: 'media outlets in network' },
	creators: { value: '5,000+', label: 'creators and KOLs' },
	events: { value: '40+', label: 'events executed' },
	brands: { value: '50+', label: 'brands supported' },
	channels: { value: '600+', label: 'distribution channels' },
	teams: { value: 'US + CN', label: 'teams in both markets' }
};

/** The thin trust strip under the hero (§5.1.2). */
export const trustStrip = [stats.outlets, stats.creators, stats.events, stats.brands, stats.teams];

export const nav = {
	links: [
		{ label: 'Home', href: '/' },
		{ label: 'Services', href: '/services/' },
		{ label: 'Case Studies', href: '/case-studies/' },
		{ label: 'Insights', href: '/insights/' },
		{ label: 'About', href: '/about/' },
		{ label: 'Contact', href: '/contact/' }
	],
	cta: 'Get in touch'
};

/**
 * Contact delivery.
 *  - formEndpoint: the Cloudflare Worker relay (infra/lead-worker/) that emails
 *    the team and upserts the lead into Flodesk. Empty until it is deployed.
 *  - email: the real inbox. With no endpoint, forms fall back to a pre-filled
 *    mailto: link so a message is never silently dropped.
 *  - turnstileSiteKey: optional Cloudflare Turnstile key; the widget is skipped
 *    entirely while it is empty.
 */
export const contactConfig = {
	formEndpoint: '',
	turnstileSiteKey: '',
	email: site.contact.email,
	phone: site.contact.phone,
	address: site.contact.address,
	offices: site.contact.areaServed
};

/** "Why ATTENCITY" — one-pager copy, which carries the numbers (§3.4). */
export const whyPoints = [
	{
		icon: 'megaphone',
		title: 'Global media & creator network',
		copy: 'Access to 1,000+ media outlets and 5,000+ creators across the U.S., China, and global markets.'
	},
	{
		icon: 'pin',
		title: 'Proven market activation experience',
		copy: '40+ events and exhibitions executed, and 50+ brands supported into the U.S. market.'
	},
	{
		icon: 'globe',
		title: 'Cross-market localization',
		copy: 'U.S. and China-based teams that rebuild the story for local context instead of translating it.'
	},
	{
		icon: 'trend',
		title: 'From attention to authority',
		copy: 'Our 3A × 4R methodology turns visibility into trust, and trust into long-term brand assets.'
	}
];

export const home = {
	title: null, // → "Attencity — Attention meets City!" via Seo defaults
	hero: {
		/** Background slider — crossfades through static/assets/attencity/events/ every
		 *  `interval` ms. Each slide is a full-size WebP with an `-800.webp` sibling for
		 *  phones (srcset). The first slide is the LCP image and is preloaded. `alt`
		 *  documents each photo; the slides render decoratively (alt="") behind the H1. */
		interval: 6000,
		slides: [
			{
				image: 'events/pre-ai-tech-week-nyc-3.webp',
				position: 'center 40%',
				alt: 'A speaker at the Pre-AI Tech Week NYC podium in front of the Silicon Valley AI Film Festival backdrop'
			},
			{
				image: 'events/ces-2026-1.webp',
				position: 'center 45%',
				alt: 'Two speakers seated on the “Go Global at CES” stage at the 2026 Speed Award World Tech Summit'
			},
			{
				image: 'events/pre-ai-tech-week-nyc-2.webp',
				position: 'center 45%',
				alt: 'Award recipients and hosts on stage at Pre-AI Tech Week NYC'
			},
			{
				image: 'events/ces-2026-8.webp',
				position: 'center 40%',
				alt: 'Five people on stage with a Speed Award trophy at CES 2026'
			},
			{
				image: 'events/shanghai-day-1.webp',
				position: 'center 55%',
				alt: 'The Summer for the City plaza and stage at Lincoln Center during Shanghai Day'
			},
			{
				image: 'events/pre-ai-tech-week-nyc-1.webp',
				position: 'center 40%',
				alt: 'A full audience watching the hosts on stage at Pre-AI Tech Week NYC'
			}
		],
		title: 'Attention meets City!',
		lead: 'Your long-term partner for cross-market, cross-city growth.',
		text: 'Helping brands localize deeply and grow sustainably in global markets.',
		primary: 'Get in touch',
		secondary: 'View Services',
		secondaryHref: '/services/'
	},
	servicesCompany: {
		eyebrow: 'Services for Company',
		title: 'We design brand systems that scale across markets, media, and distribution channels.',
		cardCta: 'Learn more',
		cta: 'All services',
		ctaHref: '/services/'
	},
	why: {
		title: 'Why Attencity',
		lead: 'Attencity combines media, creators, AI-driven distribution, and localized market strategy to help companies expand across borders with relevance, credibility, and long-term impact.',
		image: 'why-attencity-billboard.webp',
		alt: 'An Attencity digital billboard on a city street at dusk, showing a team working around a desk'
	},
	partners: {
		eyebrow: 'Partners & media',
		title: 'Backed by a broadcast partner, evidenced by the coverage.',
		placementsLabel: 'Placements in'
	},
	servicesIndividual: {
		title: 'Services for Individual',
		body: 'We help high-profile individuals — including founders, creators, artists, and public figures — build structured narrative, media, and social distribution systems that ensure consistent visibility, credibility, and long-term authority across platforms.',
		image: 'services-individual-city-glass.webp',
		alt: 'Low-angle view of glass skyscrapers reflecting the sky',
		cta: 'Personal branding',
		ctaHref: '/services/personal-branding/'
	},
	clients: {
		title: 'Our Happy Clients',
		sub: 'Trusted by brands across markets that value long-term authority, not short-term visibility.'
	},
	recentWork: {
		eyebrow: 'Recent work',
		title: 'Proof, with the numbers attached.',
		cta: 'All case studies',
		ctaHref: '/case-studies/'
	},
	latestInsights: {
		eyebrow: 'Insights',
		title: 'What we’re seeing, and where we’ve been.',
		cta: 'All insights',
		ctaHref: '/insights/'
	},
	/** Social feed marquee — clips in static/assets/attencity/social/. */
	social: {
		eyebrow: 'Follow along',
		title: '@attencitymarketing',
		href: 'https://www.instagram.com/attencitymarketing/',
		clips: Array.from({ length: 8 }, (_, i) => ({
			file: `social/attencity-social-${i + 1}.mp4`,
			poster: `social/attencity-social-${i + 1}.webp`,
			href: 'https://www.instagram.com/attencitymarketing/',
			network: 'Instagram',
			label: `Attencity social clip ${i + 1}`
		}))
	},
	contactCta: {
		eyebrow: 'Contact',
		title: 'Find a better solution for your business',
		image: 'contact-bg-woman-city-reflection.webp'
	}
};

/** Shared "Get in touch" modal copy. */
export const contactModal = {
	eyebrow: 'Contact',
	title: 'Get in touch',
	sub: 'Tell us about your market, your product, and where you want to be seen.'
};

export const servicesPage = {
	title: 'Services',
	hero: {
		eyebrow: 'What we do',
		sub: 'We design brand systems that scale across markets, media, and distribution channels.',
		image: 'services-individual-city-glass.webp'
	},
	companyLabel: 'For companies',
	individualLabel: 'For individuals',
	cardCta: 'Read more',
	cta: {
		title: 'Have any questions?',
		body: 'Tell us about your market, your product, and where you want to be seen.',
		button: 'Contact us',
		href: '/contact/'
	}
};

/** Shared copy for the service landing-page template (§5.2). */
export const servicePageChrome = {
	overviewTitle: 'Overview',
	whatWeDoTitle: 'What we do',
	howItWorksTitle: 'How it works',
	proofTitle: 'Proof',
	faqTitle: 'Frequently asked',
	relatedCaseStudies: 'Related case studies',
	relatedInsights: 'Related reading',
	cta: {
		eyebrow: 'Start a conversation',
		title: 'Tell us where you want to be seen.',
		button: 'Get in touch'
	}
};

export const aboutPage = {
	title: 'About',
	hero: {
		eyebrow: 'About Attencity',
		sub: 'A New York agency built for cross-market, cross-city growth.',
		image: 'why-attencity-billboard.webp'
	},
	whoWeAre: {
		eyebrow: 'Who we are',
		title: 'Attention meets City',
		lead: 'Attencity is a New York City–based marketing and communications firm specializing in data-driven, culturally intelligent strategies that help brands connect with diverse audiences across global markets.',
		body: [
			'Through a hybrid model of project-based engagements and long-term strategic partnerships, we deliver scalable solutions that drive visibility, engagement, and cross-border growth.',
			'The name comes from “Attention Meets City”. We believe genuine brand influence is born from the connections between people, between people and cities, and between brands and society. A city isn’t just a geographic space — it’s an ecosystem built on culture, relationships, and trust. Entering a market isn’t really about entering a channel; it’s about entering a network of relationships.',
			'Our mission is to help brands build that connection across cities and markets — moving from attention, to trust, to lasting brand equity — so brands are understood, embraced, and shared in the local context of every city.'
		],
		image: 'about-hero-desk-orange.webp',
		alt: 'Flat-lay of an orange desk with a laptop, notebook, and coffee'
	},
	purpose: {
		eyebrow: 'Vision & mission',
		title: 'Our purpose',
		lead: 'To be the long-term growth partner for founders expanding across markets and cities — helping brands build the system that takes them from being seen, to being trusted, to being chosen and invested in.',
		missionTitle: 'Our mission',
		points: [
			{
				title: 'Built for the long run, not a moment of buzz',
				copy: 'We deliver a lasting brand asset system: positioning, narrative framework, content assets, and media and capital credibility.'
			},
			{
				title: 'Built around our 4R model, to create influence that compounds',
				copy: 'Attencity’s proprietary methodology turns awareness into influence, and influence into growth opportunity.'
			},
			{
				title: 'China–US cross-cultural localization',
				copy: 'We rebuild the story for the local context, so your brand is truly understood, trusted, and shared in the US.'
			},
			{
				title: 'Hands-on partnership, systematic delivery',
				copy: 'From strategy to execution, from milestones to the long haul — we stay with you every step of the way.'
			}
		]
	},
	methodology: {
		eyebrow: 'Our methodology',
		title: '3A × 4R',
		lead: 'The “3A × 4R” framework moves a brand’s recognition (Attention) in a target market up to trust (Authority), and ultimately into a reusable, growable brand Asset. We build this through our 4R relationship-asset system, creating a compounding growth loop of Seen → Trusted → Built, so growth stays durable, repeatable, and scalable as you expand across markets.',
		threeA: [
			{ key: 'Attention', value: 'Being seen' },
			{ key: 'Authority', value: 'Being trusted' },
			{ key: 'Asset', value: 'What lasts' }
		],
		fourR: [
			{ code: 'BR', title: 'Brand Asset Building', copy: 'Positioning, narrative framework and the content assets everything else runs on.' },
			{ code: 'PR', title: 'Communications Management', copy: 'Systematic media planning that converts visibility into third-party credibility.' },
			{ code: 'CR', title: 'Channel Penetration', copy: 'Creators, commerce and offline activation that carry the story to where people buy.' },
			{ code: 'IR', title: 'Investor Relations Management', copy: 'The narrative and proof that make a brand legible to capital, not just to customers.' }
		],
		loop: ['Seen', 'Trusted', 'Built']
	},
	network: {
		eyebrow: 'Network reach',
		title: 'The rooms we can already get you into.',
		lead: 'Attencity works through an established network of media, creators and institutions across the U.S. and China. Names below indicate the network we operate in; see our case studies for placements we can evidence.',
		note: 'Media names are listed as network reach. Where we show a clipping, the placement is evidenced.'
	},
	// Founder spotlight — compiled from Lynn's public profile and Pre-AI Tech Week NYC coverage.
	founder: {
		eyebrow: 'Meet the founder',
		name: 'Lynn Zhang',
		role: 'Founder, Attencity · Director, MC International US',
		image: 'founder-lynn-zhang.webp',
		alt: 'Lynn Zhang, founder of Attencity, reading a magazine in front of a wall of fashion titles',
		lead: 'Lynn founded Attencity in New York in 2023 to help AI, retail, consumer, and K-beauty brands grow in the U.S. market through brand strategy, data analytics, and partnerships.',
		body: [
			'She came to brand-building from the data side. Before Attencity, Lynn spent six years in marketing and customer analytics at H&M, Cole Haan, and Block72, most recently as CRM & Marketing Data Manager at H&M. That background shapes how Attencity works: every campaign is built around outcomes that can be measured, not just visibility.',
			'Lynn also serves as Director at MC International US and represents Shanghai Media Group in the New York market. She opened Pre-AI Tech Week NYC with remarks on the convergence of local and global innovation ecosystems, and gave the opening remarks at the 2025 NYU Innovation Summit & Startup Competition on the idea that great innovation deserves to be seen by the world.'
		],
		facts: [
			{ label: 'Founded Attencity', value: 'New York, 2023' },
			{ label: 'Previously', value: 'H&M · Cole Haan · Block72' },
			{ label: 'Education', value: 'M.S. Integrated Marketing, New York University · B.S. Information Systems Security, Tongji University' },
			{ label: 'Focus', value: 'U.S. market growth for AI, retail, consumer, and K-beauty brands' }
		]
	},
	showTeam: false, // no team data in the deck; flip once real names/roles/photos exist
	team: {
		eyebrow: 'Our team',
		title: 'The people behind the work',
		members: [
			{ name: 'John Doe', role: 'Web designer', image: 'team-1.webp' },
			{ name: 'Jane Doe', role: 'Marketing Specialist', image: 'team-2.webp' },
			{ name: 'Mary Smith', role: 'CEO', image: 'team-3.webp' },
			{ name: 'Christina Doe', role: 'Designer', image: 'team-4.webp' },
			{ name: 'John Smith', role: 'Developer', image: 'team-5.webp' },
			{ name: 'Michael Doe', role: 'Developer', image: 'team-6.webp' }
		]
	},
	careers: {
		eyebrow: 'Careers & available jobs',
		title: 'We’re looking for a new colleague!',
		body: 'Interested in working with Attencity? Tell us about yourself and the kind of role you’re looking for.',
		button: 'Contact us',
		href: '/contact/'
	}
};

export const contactPage = {
	title: 'Contact',
	hero: {
		eyebrow: 'Contact',
		sub: 'Find a better solution for your business',
		image: 'contact-bg-woman-city-reflection.webp'
	},
	info: {
		title: 'Contact info',
		addressLabel: 'Office',
		directions: 'Get directions',
		socialLabel: 'Follow us',
		mapTitle: 'Map showing Attencity at 411 West 35th Street, New York'
	},
	form: {
		title: 'Send us a message'
	}
};

export const caseStudiesPage = {
	/** §10 Q4 in the previous plan — flip to false to hide the section and its
	 *  nav entry if the owner would rather wait before publishing client work. */
	enabled: true,
	title: 'Case Studies',
	hero: {
		eyebrow: 'Our work',
		sub: 'From attention to authority — with the numbers attached.',
		image: 'work/soho-popup-1.webp'
	},
	intro: 'Pop-ups, launches, creator parties and cross-border PR programmes we planned and ran. Every entry lists the venue, the date and what it actually produced.',
	filterAll: 'All work'
};

export const insightsPage = {
	enabled: true,
	title: 'Insights',
	hero: {
		eyebrow: 'Insights',
		sub: 'Event recaps, partnership news, and notes on cross-border growth.',
		image: 'events/ces-2026-1.webp'
	},
	intro: 'Where we have been, who we covered, and what we are learning about building brand authority across the US–China corridor.',
	filterAll: 'All posts',
	author: {
		name: 'Lynn Zhang',
		role: 'Founder, Attencity',
		image: 'founder-lynn-zhang.webp'
	}
};

export const footer = {
	menuLabel: 'Company',
	servicesLabel: 'Services',
	contactLabel: 'Contact',
	followLabel: 'Follow us',
	menu: [
		{ label: 'About', href: '/about/' },
		{ label: 'Case Studies', href: '/case-studies/' },
		{ label: 'Insights', href: '/insights/' },
		{ label: 'Contact', href: '/contact/' }
	],
	copyright: `© 2026 ${site.legalName}. All rights reserved.`
};
