// =====================================================================
// Clients, network reach and evidenced press placements.
// Source: 2026 Business Deck slides 5–12 and 19–23 (see
// docs/content-update-plan.md §3.5–§3.6). Split out of attencity.js
// because it is long, flat reference data rather than page copy.
//
// Legal note (plan §3.6): third-party *media* names are rendered as TEXT,
// never as logos, until the owner confirms permission. Only outlets with a
// screenshot in the deck appear under `placements`.
// =====================================================================

/** Client logos, white-silhouette PNGs generated by scripts/build-assets.py. */
export const clientLogos = [
	// Tech & electronics
	{ name: 'CES / Consumer Technology Association', file: 'clients/ces-cta.png', category: 'tech' },
	{ name: 'TCL', file: 'clients/tcl.png', category: 'tech' },
	{ name: 'Hisense', file: 'clients/hisense.png', category: 'tech' },
	{ name: 'Segway', file: 'clients/segway.png', category: 'tech' },
	{ name: 'Rokid', file: 'clients/rokid.png', category: 'tech' },
	{ name: 'Mobvoi', file: 'clients/mobvoi.png', category: 'tech' },
	{ name: 'Meitu', file: 'clients/meitu.png', category: 'tech' },
	{ name: 'LumiMind', file: 'clients/lumimind.png', category: 'tech' },
	{ name: 'PRIMEBOT', file: 'clients/primebot.png', category: 'tech' },
	// Lifestyle, beauty & skincare
	{ name: 'APOTHE', file: 'clients/apothe.png', category: 'beauty' },
	{ name: 'Ulike', file: 'clients/ulike.png', category: 'beauty' },
	{ name: "SAM'U", file: 'clients/samu.png', category: 'beauty' },
	{ name: 'URIID', file: 'clients/uriid.png', category: 'beauty' },
	{ name: 'NOFLEX', file: 'clients/noflex.png', category: 'beauty' },
	{ name: 'GleaMore', file: 'clients/gleamore.png', category: 'beauty' },
	// Fashion, art & entertainment
	{ name: 'Manhattan Elite Club', file: 'clients/manhattan-elite-club.png', category: 'culture' },
	{ name: 'KOSMERA', file: 'clients/kosmera.png', category: 'culture' },
	{ name: 'The Rose New York', file: 'clients/the-rose-new-york.png', category: 'culture' },
	{ name: 'Artecho', file: 'clients/artecho.png', category: 'culture' },
	// CPG & retail
	{ name: 'Gong cha', file: 'clients/gongcha.png', category: 'retail' },
	{ name: 'Ellicor', file: 'clients/ellicor.png', category: 'retail' },
	{ name: 'HungryPanda', file: 'clients/hungrypanda.png', category: 'retail' },
	{ name: 'Lelecha', file: 'clients/lelecha.png', category: 'retail' },
	// Education, services & organisations
	{ name: 'iTalkBB', file: 'clients/italkbb.png', category: 'organisations' },
	{ name: 'Brand USA', file: 'clients/brand-usa.png', category: 'organisations' },
	{ name: 'hibee', file: 'clients/hibee.png', category: 'organisations' }
];

/** Full client roster as text, by category (About page — deck s8–s12). */
export const clientCategories = [
	{
		key: 'tech',
		title: 'Tech & electronics',
		names: [
			'CES / Consumer Technology Association', 'Mobvoi', 'Meitu', 'Segway', 'TCL', 'Exumn',
			'Rokid', 'Hisense', 'PRIMEBOT', 'Altair X', 'Xtand', 'newtone', 'Snaplii',
			'SolarLink Energy Construction', 'Screna', 'LumiMind'
		]
	},
	{
		key: 'beauty',
		title: 'Lifestyle, beauty & skincare',
		names: [
			'URIID', 'NOFLEX', 'biuty', 'MiPalette (MC)', 'GOB Gorgeous Beauty', 'edensoft',
			'APOTHE', "SAM'U", 'Ulike', 'GleaMore', 'mi'
		]
	},
	{
		key: 'culture',
		title: 'Fashion, art & entertainment',
		names: [
			'Manhattan Elite Club', 'Artecho', 'Marbella', 'SVAI', 'cozy art land',
			'The Rose New York', 'Lamu', 'VShow', 'Kosmera', 'FINDU', '101 Studios'
		]
	},
	{
		key: 'retail',
		title: 'CPG & retail',
		names: ['Gong cha', 'Ellicor', 'Meirya', 'Lelecha', 'HungryPanda 熊猫外卖']
	},
	{
		key: 'organisations',
		title: 'Education, services & organisations',
		names: [
			'hibee', 'Rigel Atlas', '向美国际', 'EliteLink Education', 'GYZ Studio',
			'Merlyn for Education', 'Solo Unicorn Club', 'iTalkBB', 'GFM.News', 'EpicQuest',
			'經緯竹子 (New York Bamboo)', 'GAGRO 合抱之木', 'Brand USA', 'CSSAEA', 'Break real',
			'汉天卫视 (China TV Media Group USA)'
		]
	}
];

/** Network reach — presented as text lists, never as third-party logos. */
export const networkGroups = [
	{
		title: 'China media',
		copy: 'Through Shanghai Media Group and our own newsroom relationships.',
		names: [
			'SMG International', 'Record China', 'ENEX', 'WAM Media Group', 'STV', '看看新闻',
			'东方卫视', 'ShanghaiEye'
		]
	},
	{
		title: 'US media',
		copy: 'National, tech, business and arts desks we pitch and place into.',
		names: [
			'The Wall Street Journal', 'USA Today', 'Forbes', 'Billboard', 'The Associated Press',
			'Variety', 'Yahoo Finance', 'Wired', 'Business Insider', 'NBC', 'TechCrunch',
			'VentureBeat', 'Bloomberg', 'The Verge', 'IEEE Spectrum', 'TechRadar',
			'Digital Trends', 'MarketWatch', 'CNBC', 'Investopedia', 'Quartz', 'Morningstar',
			'Artforum', 'ARTnews', 'The Art Newspaper', 'artnet', 'frieze', 'Hyperallergic'
		]
	},
	{
		title: 'Institutions & associations',
		copy: 'Universities, alumni networks and cultural organisations across the US.',
		names: [
			'NYU CSSA', 'Columbia CUCSSA', 'Cornell CSSA',
			'Greater New York Chinese Association for Science & Technology',
			'Shanghai Association in USA', 'AIRA', 'AAAA', 'Manhattan Elite Club',
			'Solo Unicorn Club', 'New York Chinese Cultural Center',
			'Chinese Progressive Association', 'CAPSC', 'Creative China Center',
			'大紐約華人聯合會', '~20 Chinese university alumni associations'
		]
	}
];

/**
 * Outlets we can point at a specific, evidenced placement (deck s19, s22–s23).
 * `proof` is the case study or post that shows the clipping.
 */
export const placements = [
	{ outlet: 'The Wall Street Journal', proof: 'shanghai-day-lincoln-center-2025', type: 'insight' },
	{ outlet: 'USA Today', proof: 'shanghai-day-lincoln-center-2025', type: 'insight' },
	{ outlet: 'Business Insider', proof: 'soho-lunar-new-year-valentines-popup', type: 'case-study' },
	{ outlet: 'The Associated Press', proof: 'soho-lunar-new-year-valentines-popup', type: 'case-study' },
	{ outlet: 'Benzinga', proof: 'soho-lunar-new-year-valentines-popup', type: 'case-study' },
	{ outlet: 'StreetInsider', proof: 'soho-lunar-new-year-valentines-popup', type: 'case-study' },
	{ outlet: 'AsiaOne', proof: 'soho-lunar-new-year-valentines-popup', type: 'case-study' },
	{ outlet: 'Barchart', proof: 'soho-lunar-new-year-valentines-popup', type: 'case-study' },
	{ outlet: 'The Globe and Mail', proof: 'soho-lunar-new-year-valentines-popup', type: 'case-study' },
	{ outlet: 'Digital Journal', proof: 'soho-lunar-new-year-valentines-popup', type: 'case-study' },
	// Held back with the 2021–2022 placements case study (plan §10 Q5).
	{ outlet: 'Yahoo Finance', proof: 'cross-border-pr-placements', type: 'case-study' },
	{ outlet: 'MarketWatch', proof: 'cross-border-pr-placements', type: 'case-study' },
	{ outlet: 'Seeking Alpha', proof: 'cross-border-pr-placements', type: 'case-study' },
	{ outlet: 'Cision / PR Newswire', proof: 'cross-border-pr-placements', type: 'case-study' },
	{ outlet: 'Boston Herald', proof: 'cross-border-pr-placements', type: 'case-study' }
];
