# ============================================================================
#  Attencity — WordPress deployment
#
#  Target: WordPress.com. SSH and SFTP there need a Business or Commerce plan;
#  on Premium there is no shell at all and the theme has to go up through
#  Appearance -> Themes -> Upload instead. See docs/hosting-facts.md.
#
#  Note the domain still resolves to the old SiteGround server until its DNS
#  is repointed — `make dns-status` shows where it actually goes.
#
#  Quick start (once the site is on Business or Commerce)
#    1. WordPress.com -> Settings -> SFTP/SSH -> create credentials.
#    2. Add ~/.ssh/wpcom_attencity_ed25519.pub under Security -> SSH key.
#    3. cp .live-sites/_template.mk .live-sites/attencity.mk  and fill it in.
#    4. make test-connection          <-- the go/no-go gate. Nothing proceeds
#                                         until this passes.
#    5. make build-and-push
#
#  Everything under wordpress-theme/ is generated by the theme build script.
#  Never hand-edit it — the next build overwrites it.
# ============================================================================

# Per-site credentials live in gitignored fragments so nothing sensitive is
# committed. Pass SITE=<key> to load .live-sites/<key>.mk.
SITE ?=

SITES_AVAILABLE := $(sort $(patsubst .live-sites/%.mk,%,$(filter-out .live-sites/_template.mk,$(wildcard .live-sites/*.mk))))

ifneq ($(SITE),)
  SITE_FILE := .live-sites/$(SITE).mk
  ifeq ($(wildcard $(SITE_FILE)),)
    $(error SITE=$(SITE) requested but $(SITE_FILE) does not exist. Copy .live-sites/_template.mk to $(SITE_FILE) and fill it in.)
  endif
  include $(SITE_FILE)
else ifeq ($(words $(SITES_AVAILABLE)),1)
  # Exactly one fragment present: use it without needing SITE= on every command.
  SITE := $(SITES_AVAILABLE)
  include .live-sites/$(SITE).mk
endif

# ----- SSH connection (?= so a .live-sites fragment can override) -----
# WordPress.com uses one shared host for every site; the username is generated
# per site in the dashboard, so it is the only value that cannot be defaulted.
# The key is dedicated to WordPress.com rather than shared with the SiteGround
# client sites, so a problem at one vendor stays at that vendor.
WP_USER           ?= REPLACE_WITH_SSH_USER
WP_DOMAIN         ?= attencity.com
WP_HOST           ?= ssh.wp.com
WP_PORT           ?= 22
WP_IDENTITY_FILE  ?= ~/.ssh/wpcom_attencity_ed25519

# The real public domain, used only by the read-only `make dns-status`.
LIVE_DOMAIN               ?= attencity.com

# ----- WordPress paths on the server -----
# WordPress.com Atomic puts the site under /srv/htdocs. Confirm it on the first
# connection (`make ssh`, then `pwd` and `ls`) before trusting a push.
WP_DOCROOT        ?= /srv/htdocs
WP_THEME_NAME     ?= attencity
WP_REMOTE_PATH    ?= $(WP_DOCROOT)/wp-content/themes/$(WP_THEME_NAME)/

# ============================================================
#  Nothing below here should need editing
# ============================================================

LOCAL_THEME_DIR   := wordpress-theme
WP_DIR    := ./siteground
LIVE_CONTENT_DIR  := .content-sync
MERGE_SCRIPT      := scripts/merge-live-content.mjs

RSYNC_OPTS      := -avz --delete --exclude='.DS_Store' --exclude='*.zip' --exclude='node_modules'
RSYNC_SSH_OPTS  := -e "ssh -p $(WP_PORT) -i $(WP_IDENTITY_FILE) -o IdentitiesOnly=yes"
RSYNC_HOST      := $(WP_USER)@$(WP_HOST)
SSH_OPTS        := -p $(WP_PORT) -i $(WP_IDENTITY_FILE) -o IdentitiesOnly=yes
WP              := cd $(WP_DOCROOT) && wp

.PHONY: help info preflight test-connection ssh connect build push build-and-push \
        pull purge-cache push-functions push-styles push-header \
        pull-content check-content-drift list-sites push-all build-and-push-all dns-status

.DEFAULT_GOAL := help

help:
	@echo "════════════════════════════════════════════════════════════════"
	@echo "  Attencity — WordPress deployment (SiteGround)"
	@echo "════════════════════════════════════════════════════════════════"
	@echo ""
	@echo "Start here:"
	@echo "  make preflight            Check what is still missing before deploying"
	@echo "  make test-connection      Verify SSH works — the go/no-go gate"
	@echo ""
	@echo "Deploy:"
	@echo "  make build-and-push       Build the theme, rsync it up, purge caches"
	@echo "  make build                Build wordpress-theme/ locally only"
	@echo "  make push                 Rsync the existing wordpress-theme/ (no rebuild)"
	@echo "  make push-functions       Push functions.php alone (fast iteration)"
	@echo "  make push-styles          Push style.css alone"
	@echo "  make push-header          Push header.php + favicon"
	@echo "  make pull                 Download the live theme into ./siteground/"
	@echo "  make purge-cache          wp cache flush + wp sg purge"
	@echo ""
	@echo "Content sync (live WordPress is the source of truth for copy):"
	@echo "  make check-content-drift  Fail if the live site has edits this repo lacks"
	@echo "  make pull-content         Merge live edits into local content defaults"
	@echo ""
	@echo "Connection:"
	@echo "  make info                 Show the resolved configuration"
	@echo "  make dns-status           Where $(LIVE_DOMAIN) actually resolves today"
	@echo "  make ssh / connect        Interactive shell on the live server"
	@echo "  make list-sites           List configured .live-sites/ fragments"
	@echo ""
	@echo "  Append SITE=<key> to target a site configured in .live-sites/<key>.mk."
	@echo ""

info:
	@echo "Site:          $(if $(SITE),$(SITE) (from .live-sites/$(SITE).mk),<Makefile defaults — no fragment loaded>)"
	@echo "Host:          $(WP_HOST)"
	@echo "User:          $(WP_USER)"
	@echo "Port:          $(WP_PORT)"
	@echo "Identity file: $(WP_IDENTITY_FILE)"
	@echo "Docroot:       $(WP_DOCROOT)"
	@echo "Theme path:    $(WP_REMOTE_PATH)"
	@echo "Local theme:   $(LOCAL_THEME_DIR)/"

# Tells you exactly what is still missing, instead of failing with a cryptic
# ssh or rsync error. Safe to run at any time.
preflight:
	@echo "Preflight for Attencity deployment"
	@echo "──────────────────────────────────"
	@ok=1; \
	if [ "$(WP_USER)" = "REPLACE_WITH_SSH_USER" ]; then \
	  echo "  ✗ SSH username not set   — WordPress.com -> Settings -> SFTP/SSH (needs Business)"; ok=0; \
	else echo "  ✓ SSH username          $(WP_USER)"; fi; \
	echo "  ✓ SSH host              $(WP_HOST)"; \
	key=$$(eval echo $(WP_IDENTITY_FILE)); \
	if [ -f "$$key" ]; then echo "  ✓ Private key           $$key"; \
	else echo "  ✗ Private key missing   $$key"; ok=0; fi; \
	if [ -z "$(SITES_AVAILABLE)" ]; then \
	  echo "  ✗ No .live-sites/*.mk    — cp .live-sites/_template.mk .live-sites/attencity.mk"; ok=0; \
	else echo "  ✓ Site fragment(s)      $(SITES_AVAILABLE)"; fi; \
	if grep -q '"build:wordpress"' package.json 2>/dev/null; then \
	  echo "  ✓ build:wordpress script"; \
	else echo "  ✗ build:wordpress script missing — Part 1 of the playbook (theme generator)"; ok=0; fi; \
	echo ""; \
	if [ $$ok -eq 1 ]; then echo "All set. Next: make test-connection"; \
	else echo "Fill the gaps above, then re-run: make preflight"; exit 1; fi

test-connection:
	@echo "🔌 Testing SSH connection…"
	@ssh $(SSH_OPTS) $(RSYNC_HOST) "echo '✅ Connected.'; echo; uname -a; echo; wp --version || echo '⚠️  wp-cli not found on PATH'"

ssh connect:
	@ssh $(SSH_OPTS) $(RSYNC_HOST)

build:
	@if ! grep -q '"build:wordpress"' package.json 2>/dev/null; then \
	  echo "❌ No 'build:wordpress' script in package.json."; \
	  echo "   The theme generator is Part 1 of docs/SPA-TO-WORDPRESS-THEME-PLAYBOOK.md."; \
	  exit 1; \
	fi
	@pnpm run build:wordpress

push:
	@if [ ! -d "$(LOCAL_THEME_DIR)" ]; then \
		echo "❌ $(LOCAL_THEME_DIR)/ does not exist. Run: make build"; exit 1; \
	fi
	@echo "⬆️  Pushing $(LOCAL_THEME_DIR)/ → $(WP_REMOTE_PATH)"
	@rsync $(RSYNC_OPTS) $(RSYNC_SSH_OPTS) --progress $(LOCAL_THEME_DIR)/ $(RSYNC_HOST):$(WP_REMOTE_PATH)
	@echo "✅ Theme uploaded."

build-and-push: build push purge-cache
	@echo "🎉 Deployment complete."

pull:
	@mkdir -p $(WP_DIR)
	@rsync -avz $(RSYNC_SSH_OPTS) --progress $(RSYNC_HOST):$(WP_REMOTE_PATH) $(WP_DIR)/
	@echo "✅ Live theme downloaded to $(WP_DIR)/"

purge-cache:
	@echo "🧹 Purging caches…"
	@ssh $(SSH_OPTS) $(RSYNC_HOST) "$(WP) cache flush" || echo "⚠️  Could not flush the WP object cache — do it in Site Tools."
	@ssh $(SSH_OPTS) $(RSYNC_HOST) "$(WP) sg purge" 2>/dev/null || echo "   (no host-level cache command — clear the edge cache from the dashboard if needed)"

push-functions:
	@rsync -avz $(RSYNC_SSH_OPTS) --progress $(LOCAL_THEME_DIR)/functions.php $(RSYNC_HOST):$(WP_REMOTE_PATH)
	@$(MAKE) --no-print-directory purge-cache

push-styles:
	@rsync -avz $(RSYNC_SSH_OPTS) --progress $(LOCAL_THEME_DIR)/style.css $(RSYNC_HOST):$(WP_REMOTE_PATH)

push-header:
	@rsync -avz $(RSYNC_SSH_OPTS) --progress $(LOCAL_THEME_DIR)/header.php $(LOCAL_THEME_DIR)/favicon.png $(RSYNC_HOST):$(WP_REMOTE_PATH)
	@$(MAKE) --no-print-directory purge-cache

# ------------------------------------------------------------------ content
# Live inline edits are stored in the WordPress database and SHADOW the local
# defaults. A stale local default is invisible on the live site right up until
# someone resets content or greps the repo for copy that no longer matches
# production. These two targets close that trap. They need the merge script
# from Part 4 of the playbook.

$(LIVE_CONTENT_DIR)/.exported:
	@mkdir -p $(LIVE_CONTENT_DIR)
	@ssh $(SSH_OPTS) $(RSYNC_HOST) "$(WP) option list --search='xo_global_*' --format=json" \
	  > $(LIVE_CONTENT_DIR)/options.json
	@ssh $(SSH_OPTS) $(RSYNC_HOST) "$(WP) option get xo_route_overrides --format=json 2>/dev/null || echo '{}'" \
	  > $(LIVE_CONTENT_DIR)/route-overrides.json
	@touch $@

pull-content:
	@if [ ! -f "$(MERGE_SCRIPT)" ]; then echo "❌ $(MERGE_SCRIPT) not written yet (playbook Part 4.3)."; exit 1; fi
	@echo "⬇️  Exporting live content from $(WP_DOMAIN)…"
	@rm -f $(LIVE_CONTENT_DIR)/.exported
	@$(MAKE) --no-print-directory $(LIVE_CONTENT_DIR)/.exported
	@node $(MERGE_SCRIPT)

check-content-drift:
	@if [ ! -f "$(MERGE_SCRIPT)" ]; then echo "❌ $(MERGE_SCRIPT) not written yet (playbook Part 4.3)."; exit 1; fi
	@rm -f $(LIVE_CONTENT_DIR)/.exported
	@$(MAKE) --no-print-directory $(LIVE_CONTENT_DIR)/.exported
	@node $(MERGE_SCRIPT) --check

# ------------------------------------------------------------------ DNS
# Read-only. attencity.com's DNS zone lives at WordPress.com (ns1-3.wordpress.com)
# even though the site is hosted on SiteGround, so this watches both ends.
# Public resolvers are asked on purpose so a local cache cannot hide propagation.
dns-status:
	@ip=$$(dig +short $(WP_DOMAIN) A | head -1); \
	echo "Current A record for $(WP_DOMAIN):  $$ip"; \
	echo ""; \
	for r in 1.1.1.1 8.8.8.8; do \
	  echo "── as seen by $$r"; \
	  echo "  NS   $(LIVE_DOMAIN)        $$(dig +short @$$r $(LIVE_DOMAIN) NS  | sort | tr '\n' ' ')"; \
	  echo "  A    $(LIVE_DOMAIN)        $$(dig +short @$$r $(LIVE_DOMAIN) A   | sort | tr '\n' ' ')"; \
	  echo "  www  www.$(LIVE_DOMAIN)    $$(dig +short @$$r www.$(LIVE_DOMAIN)  | tr '\n' ' ')"; \
	  echo "  MX   $(LIVE_DOMAIN)        $$(dig +short @$$r $(LIVE_DOMAIN) MX  | tr '\n' ' ')"; \
	  echo "  TXT  $(LIVE_DOMAIN)        $$(dig +short @$$r $(LIVE_DOMAIN) TXT | tr '\n' ' ')"; \
	done; \
	echo ""; \
	title=$$(curl -sk --max-time 10 https://$(LIVE_DOMAIN)/ | grep -o '<title>[^<]*' | head -1 | sed 's/<title>//'); \
	echo "The live site currently answers with title:  $${title:-<no title>}"

list-sites:
	@echo "Configured sites in .live-sites/ ($(words $(SITES_AVAILABLE))):"
	@for s in $(SITES_AVAILABLE); do echo "  • $$s"; done
	@echo ""
	@echo "Usage: make build-and-push SITE=<key>"

# ------------------------------------------------------------------ fan-out
push-all:
	@if [ -z "$(SITES_AVAILABLE)" ]; then echo "No .live-sites/*.mk configured."; exit 1; fi
	@echo "Push wordpress-theme/ to ALL $(words $(SITES_AVAILABLE)) sites:"
	@for s in $(SITES_AVAILABLE); do echo "    - $$s"; done
	@printf "Continue? [y/N] " && read ans && [ "$$ans" = "y" ] || { echo "Aborted."; exit 1; }
	@failed=""; \
	for s in $(SITES_AVAILABLE); do \
		echo ""; echo "═══ [$$s] ═══"; \
		if $(MAKE) --no-print-directory push SITE=$$s; then \
			$(MAKE) --no-print-directory purge-cache SITE=$$s || true; \
		else \
			echo "❌ push failed for $$s — continuing"; failed="$$failed $$s"; \
		fi; \
	done; \
	echo ""; \
	if [ -n "$$failed" ]; then echo "⚠️  Failures:$$failed"; exit 1; \
	else echo "🎉 Pushed to all $(words $(SITES_AVAILABLE)) sites."; fi

build-and-push-all: build
	@$(MAKE) --no-print-directory push-all
