<!-- "Our Happy Clients" — dark band, white-silhouette logos generated by
     scripts/build-assets.py from the deck's client slides. -->
<script>
	import { home, clientLogos, asset, dims } from '$lib/content/attencity.js';
	import { reveal } from '$lib/actions.js';
	import { editableImage } from '$lib/wp/actions.svelte.js';
	const c = home.clients;
</script>

<section class="page-section page-section--dark padding-md" id="clients">
	<div class="container container--lg">
		<div class="content-blocks text-center" use:reveal>
			<div class="content-blocks__block"><h2 class="section-title">{c.title}</h2></div>
			<div class="content-blocks__block"><p class="section-sub">{c.sub}</p></div>
		</div>
		<ul class="client-grid" use:reveal>
			{#each clientLogos as l (l.file)}
				<li class="client-logo"><img src={asset(l.file)} use:editableImage={l.file} width={dims(l.file)?.width} height={dims(l.file)?.height} alt={l.name} loading="lazy" decoding="async" /></li>
			{/each}
		</ul>
	</div>
</section>
